github/relative-time-element

- examples/polymer.html
- test/relative-time.js
- test/test.html
- test/time-until.js
- time-elements.js
Why are we soooo concerned with the past? The future is where it's at!!! :rocket: :dizzy: 
We are looking at starting to use web components for travel applications and many of the dates and times associated are in the future. (I did find one lone place for future dates on GitHub, the milestone due date...so it at least has _some_ GH application.)
This PR adds relative-time results that are based off of the same time-ago intervals, just oriented towards the future. "3 days from now", "1 year from now", etc. It also adds a "time-until" option to counter "time-ago" in which the browser will ALWAYS give a future date.
There are several structural changes I made in able to do this so please take a look and provide any feedback.  
Open to any feedback, especially on the wordage...I went back …
> Allow relative-time to handle future dates

- README.md
- examples/polymer.html
- test/relative-time.js
- test/test.html
- test/time-until.js
- time-elements.js
This is a continuation of @markmcspadden's excellent pull from a year and a half ago: #42 (which is also related to #38).
Basically, time-elements should support future dates too. I'm living in the future so the present is my past, time-elements is a present, merge if tests pass (they do).
The majority of this is pulled from @markmcspadden's work; I just updated the syntax from the deprecated `<time is="local-time">` form and updated the README.
This pull adds an additional `time-until` element (which we can axe if it's not worthwhile), and it updates `relative-time` to see the future, too.
/cc @josh @dgraham @github/techno
> Future time redux

- time-elements.js
Chrome doesn't deal well with [new timezones added to Windows](https://blogs.technet.microsoft.com/dst2007/2016/06/02/introducing-new-windows-time-zones/).
Ocassionally when `new Intl.DateTimeFormat()` is called without being given an explicit timezone, it will error out with:
RangeError: Unsupported time zone specified undefined
Since there's nothing we can do about this right now, simply ignore the error and hope that Chrome is going to fix this in the future.
/cc @dgraham
> Encapsulate all DateTimeFormat calls to work around Chrome bug

- .eslintignore
- .travis.yml
- Makefile
- package.json
Switches custom phantomjs fetching code to caching the npm phantomjs-prebuilt package.
* Sets up phantomjs binary locally on macOS when missing. For an example, I don't have phantomjs installed via homebrew.
* Ensures consistent phantomjs version locally and in CI.
* Less code.
Speed seems uneffected.
**master**
`npm install` (w/o phantomjs-prebuilt package) 12.44s
**phantomjs-cache**
Uncached `npm install` 21.85s
Cached `npm install`13.23s
##
CC: @mislav
> Use phantomjs-prebuilt

- README.md
- examples/polymer.html
- package-lock.json
- package.json
- rollup.legacy-config.js
- Add required polyfills
- Build with template literal transformation
- Update readme for browser support (matches https://github.com/webcomponents/webcomponentsjs#browser-support)
> Making sure example works in old Safari and IE 11

- README.md
- examples/polymer.html
1. Change `webcomponent-lite.js` to `webcomponent-hi-ce.js` because we don't need Shady DOM/CSS. [The differences](https://github.com/webcomponents/webcomponentsjs/tree/068cfc9068cedf2876a5363cdfd4912cc3801bd4#how-to-use).
2. Individually include the polyfills that used to come with `webcomponents-lite.js`.
I think we are ready for v1! Yeah?
> Update polyfill requirement and example

- src/local-time-element.js
This patch checks if a `<local-time />` element already exists before we register it on the page and only registers the element if there isn't one already registered.
> 🔍check if `<local-time />` is defined before registering

- test/relative-time.js
Adding these tests since the `Intl.RelativeTimeFormat` API doesn't support messages such as `a minute ago`. Having these tests will be useful so that we're aware of those breaking changes when we implement #98.
Ref: https://github.com/tc39/proposal-intl-relative-time#example-1
> Add tests for special cases in relative-time

- src/index.js.flow
At github we are trying to extend one of the elements and using it in application code but flow keeps complaining that `_date` isn't defined on the element since we decided not to ship it with the flow definitions
This PR adds the property back in so we can access it and unblock the PR.
Ref: https://github.com/github/time-elements/pull/106#discussion_r283850992
Ref: https://github.com/github/github/pull/115283#issuecomment-492978635
> Expose faux private field 

- src/relative-time.js
- src/utils.js
- test/relative-time.js
- test/time-ago.js
- test/time-until.js
Aims to implement https://github.com/github/time-elements/issues/98.
**To-do**
> Use Intl.RelativeTimeFormat

- src/relative-time.js
- test/time-ago.js
I think we were erronusly only displaying "x months ago" when the time elapsed was 31-45 days. This patch makes sure we are showing "x months ago" when the time elapsed is 31days - 11 months.
Fixes: #113
> Make sure to format months ago correctly

- package-lock.json
- package.json
I think we want to publish a non beta version 3.0.0 before merging this and then we can follow the normal playbook of:
- Bumping the patch version.
- Publishing to npm.
- Deprecate the package without the scope with a message pointing to new package name.
Ref: https://github.com/github/web-systems/issues/216
> Rename package to include the @github scope.

- src/extended-time-element.js
Fixes #130 
I tried adding a test case here to use a MutationObserver to ensure that we weren't continuously calling the callback, but I couldn't get it to work.
If anyone has any suggestions on a good way to write a test, let me know!
> Prevent infinite loop when title attribute is changed

- src/relative-time.js
- test/time-ago.js
This change increases the month cutoff from 12 to 18 months meaning that months > 12 < 18 will be displayed as `'x months ago'` instead  of `'last year'`. Months >18 will be displayed as `'x years ago'`.
This is to prevent `'last year'` showing up in January 2020 and you are viewing a `<time-ago>` element set to November 2018. Since it's more than 12 months we'll round it down to 1 year, parse it as a years ago and `Intl.RelativeTimeFormat` will format it as `'last year'`.
Ref: https://github.com/github/github/issues/132315
> Changes to last year format

- test/time-ago.js
In #133 I made changes that were backed up by tests. Those tests relied on a mock of `Date` which did not work. The tests only ran green because I made the oversight of using current dates as the freeze date. Now that some time has passed, the tests are failing on `master` and this was discovered by @muan in #138.
This change changes the mock to _actually_ freeze the time and fixes a off by one error in the tests.
> Fix bad mock

- package.json
- src/extended-time-element.ts
- test/local-time.js
Changing the `time-zone-name` attribute does not trigger a re-render of the `<local-time>` component. This behavior is a bug that I'm fixing in this pull request by adding `time-zone-name` to the list of observed attributes in `ExtendedTimeElement`.
> Note that to get the attributeChangedCallback() callback to fire when an attribute changes, you have to observe the attributes. This is done by specifying a static get observedAttributes() method inside custom element class - this should return  an array containing the names of the attributes you want to observe.
https://developer.mozilla.org/en-US/docs/Web/Web_Components/Using_custom_elements
To be able to test this change, we need to pin the timezone. I pinned it to Dubai time since it seems to me to be a well-supported timezone but not …
> Observe time zone name attribute

- README.md
<https://caniuse.com/#feat=custom-elementsv1> is being redirected to <https://caniuse.com/custom-elementsv1> anyway, but the latter is visibly faster to me.
If you let me or want me to, I'll change the URL for each component of <https://github.com/github/github-elements> :)
> Update caniuse URL to new pattern

- examples/index.html
> "Future Date"-values are now future dates

- src/index.ts
This PR adds `.js` extensions to all the import paths in `index.ts`. This is necessary to ensure that the output `dist/index.d.ts` file also contains those extensions, which is necessary for this package to typecheck correctly for consumers that are using ES Modules.
Closes #167.
> Add file extensions to imports for ES Module support

- src/extended-time-element.ts
- src/local-time-element.ts
- src/relative-time-element.ts
- src/relative-time.ts
- src/time-ago-element.ts
- src/time-until-element.ts
In #168, I unfortunately forgot to add extensions to all the other files. This is necessary because their imports still appear in the generated `.d.ts` files.
> Add extensions to all imports

- .eslintrc.json
- package-lock.json
- package.json
- src/relative-time-element.ts
#168 and #169 added file extensions to imports, but it's easy to accidentally forget these in the future. As a safety net, I'd like to add the  `import/extensions` rule.
I also update all of our dependencies and tweaked the eslint rules to match existing code
> Dependency updates and require extensions in imports

- README.md
> Fix closing tag for `time-until` in documentation

- src/extended-time-element.ts
- src/relative-time-element.ts
- src/relative-time.ts
- test/relative-time.js
This adds tense to relative-time, which enables it to be used like `time-ago` or `time-until`. This makes the logic within `relative-time` _slightly_ more complicated but with subsequent PRs we'll be able to drastically reduce complexity within `time-ago` and `time-until`, and we can remove them entirely in a major version bump.
> add tense to relative-time

- src/time-ago-element.ts
- src/time-until-element.ts
Now RelativeTimeElement supports `tense`, the `TimeAgo` and `TimeUntil` elements can be drastically simplified by fixing the `tense` value for these elements.
> simplify time-until/ago elements

- src/relative-time-element.ts
- src/relative-time.ts
- test/relative-time.js
This starts the process of moving code from `RelativeTime` to `RelativeTimeElement` by moving the `toString()` method into `RelativeTime`, simplifying the `RelativeTime` class.
This also makes the `on ` prefix on RelativeTime overridable by passing in the `prefix` attribute (which I've marked as deprecated as we'll want to remove it in a future major version).
> Extract tostring from relative time into element

- src/relative-time-element.ts
- src/relative-time.ts
- src/utils.ts
In an effort to simplify and reduce the amount of code in this repo we've inlined and simplified code in `utils.ts` that is only used in one place for `<relative-time>`.
> Inline utilities only used in `<relative-time>`

- src/relative-time-element.ts
- test/relative-time.js
This adds all the tests from local-time into the relative-time test suite, and adds the necessary fields (`timeZoneName`) to allow `relative-time` to operate in the same manner as `local-time`.
> add relative-time tests for local-time

- src/relative-time-element.ts
This adds setters for all values, allowing them to be set to update the attribute as well as got.
> add setters for all attributes

- examples/index.html
- src/relative-time-element.ts
This takes the work from #122 and updates it in line with the changes to the codebase. (Subsequently, this closes #122)
When updating `nowElements`, figure out how far away in time the nearest one is to ensure timely updates:
If an element is within
- one minute from now, update a second after last run
- one hour from now - update a minute after last run
- more than one hour from now - update hourly after last run
Switching to setTimeout ensures that with a lot of attached instances, where a run might take a while, we won't schedule the next run until after all elements have been updated.
Also fire a `relative-time-updated` event if `textContent` changes in case this needs to be acted on.
Additionally it "unobserves" elements that are no longer displaying relative time, meaning the amount …
> RelativeTimeElement: Progressive time update intervals

- src/relative-time-element.ts
- test/local-time.js
- test/relative-time.js
- test/time-ago.js
- test/time-until.js
This changes the `<relative-time>` element to use a ShadowRoot, instead of mutating the `textContent` directly. This is useful because it enables `<relative-time>` to mutate its own display without interfering with components or frameworks which assess or otherwise depend on the tree below `<relative-time>`; for example frameworks like React which maintain a virtual DOM, or code which leverages Mutation Observers to track changes to the tree.
The trade-off here is that it is not possible to assert the display of the date via `el.textContent`, as this would represent the light HTML tree (so likely the original date rendered server side). Consequently the tests need to change to accommodate this.
> Switch element to defining content within ShadowDOM

- src/datetimeformat-ponyfill.ts
- src/local-time-element.ts
- src/relative-time-element.ts
This PR introduces a `DateTimeFormat` ponyfill, which allows us to drop it in place of `Intl.DateTimeFormat`. This then allowed a larger refactor where we can drop parts of the codebase where we emulated `DateTimeFormat` behavior using strftime. Instead, the ponyfill does that and the `relative-time` and `local-time` code can be greatly simplified.
I think in the major version release, we should drop both the `DateTimeFormat` and `RelativeTime` ponyfills as these are very well supported in evergreen browsers. (`DateTimeFormat` works back to IE11 & Safari 10, while `RelativeTime` works back to Safari 14)
> Local time refactor

- src/datetimeformat-ponyfill.ts
- src/relative-time-ponyfill.ts
- src/relative-time.ts
- test/datetimeformat-ponyfill.ts
- test/relativetimeformat-ponyfill.ts
In #194 I forgot to add tests, which I had written. I've written some more now for both ponyfills so that they align with what the real Intl objects do (at least for `'en'` locale :smile:)
> add tests for ponyfills

- src/relative-time-element.ts
- src/relative-time.ts
- src/time-ago-element.ts
- src/time-until-element.ts
This extracts out the coupling of `RelativeTimeFormat` from our `RelativeTime` class - which now instead returns a tuple of `number, Unit`, reflecting just the rounded unit of time that should be rendered. This allows us to subsequently refactor the `RelativeTime` class closer to the proposed web platform primitive Temporal.Duration, which will come in a follow up PR :smile:
> refactor relative-time to remove RelativeTimeFormat

- package-lock.json
- package.json
- src/duration.ts
- test/duration.ts
This refactors our `duration.ts` file to include a class which aligns closer to Temporal.Duration. In fact I even added `@js-temporal/polyfill` as a devdependency and ran some tests comparing our `Duration` class to the `Temporal.Duration` class.
This is useful because `threshold` can be set to a string that `Temporal.Duration.from` would take, and so the closer we align to that the better. Additionally, the closer our class is to `Temporal.Duration`, the easier it'll be to delete it one day.
> Make duration class

- src/relative-time-element.ts
- test/relative-time.js
`update()` is getting a bit too eagerly called in the latest version, which is causing many time elements on the page to stack overflow. This mitigates that in a few ways:
- Ensure if the `attributeChangedCallback` is called with the same value, that it doesn't call `update`.
- Ensure that if the `title` attribute changes, it doesn't lead to an `update`.
- Ensure that when an element gets `unobserve`d, that it doesn't trigger an update of all elements (as there's no point in updating eagerly here - the current `setTimeout` could already be eager if the element being unobserved is the latest element).
- Ensure that when an element _does_ get `observe`d, that it doesn't immediately trigger an update. Rather, it determines if it _should_ update sooner than the next scheduled update, and if …
> avoid eagerly calling this.update()

- src/relative-time-element.ts
In testing this in various browsers I had noticed when it needs to fall back to the ponyfills, it won't correctly do so due to a bug (I think from refactoring) the feature detection. This fixes that.
> fix bug in Intl detection

- src/relative-time-element.ts
- test/relative-time.js
We've encountered a regression that entered into `<relative-time>` when it comes to invalid usage. Prior to using shadowdom, invalid usage would not change the text content, which means it would be left with whatever was server rendered. When introducing the shadowdom, we implicitly do not render whatever textContent is present in the lightdom, and so if an invalid use of the element occurs, the shadowdom will be empty, in other words nothing will be rendered.
In order to maintain compatibility, this PR introduces a fallback behaviour where if `getFomrattedDate()` is empty, it will intentionally copy over the lightdom textContent into the shadowdom, emulating the old behaviour.
> ensure invalid dates fallback to lightdom textcontent

- README.md
- examples/index.html
- src/duration-format.ts
- src/relative-time-element.ts
- test/relative-time.js
This adds a new `elapsed` format, which displays the compact representation of how long has elapsed between the provided `datetime` and the current date.
This is designed to replace an extended element we have in `github/github` called `precise-time-ago`, which aims to be like `<time-ago format=micro>` but will display _all_ units, not just the largest unit.
> add elapsed time format

- src/relative-time-element.ts
- src/strftime.ts
- test/relative-time.js
- test/strftime.ts
This change supports localisation of Weekday and Month names in `strftime` formats. 
Fixes #205
> Strftime localisation

- src/relative-time-element.ts
- src/strftime.ts
In order for this to be usable in Primer React, we need to remove the references to `window` which the gatsby build doesn't seem to like. Lucky that's easy enough.
https://github.com/primer/react/actions/runs/3525178884/jobs/5911569573
This PR changes the `'Intl' in window && 'XX' in Intl` checks to instead be `typeof Intl !== 'undefined' && 'XX' in Intl`. This is pretty much identical logic, but avoids referencing the `window` global and as such this code can be loaded in NodeJS without error.
> use `Intl` without window prefix

- src/index.ts
- src/local-time-element.ts
- src/relative-time-element.ts
- src/time-ago-element.ts
- src/time-until-element.ts
- test/constructor.js
- test/local-time.js
- test/relative-time.js
- test/time-ago.js
- test/time-until.js
- test/title-format.js
This moves the `customeElements.define` calls from each respective element and into the index.js file. This is useful for if we wish to load the components classes without defining the custom element.
In addition, this changes the pattern of how we register the custom elements, to allow for HMR, as we did in
https://github.com/github/catalyst/pull/197.
> move customElements define calls to index.js and refactor

- package.json
- src/index.ts
- src/local-time-element-define.ts
- src/relative-time-element-define.ts
- src/time-ago-element-define.ts
- src/time-until-element-define.ts
Following a discussion with @koddsson - this PR attempts to create a pattern of module definitions within our custom elements.
Effectively, all custom elements can be imported via their bare specifier (so in this case `@github/relative-time-element`). This _will not import the custom element definition_ (though it does here, to avoid breaking changes). Instead one will have to `import '@github/relative-time-element/define'`. This will then import the code which defines the element.
In addition, for this element (at least for now - though these will be removed in a breaking release) the following imports are also enabled:
- `'@github/time-elements` - all classes
- `'@github/time-elements/define` - all classes and their custom element definitions
- `'@github/time-elements/relative-time` - …
> add `define` export for custom element registration

- src/relative-time-element.ts
- test/relative-time.js
There was a typo in the `observedAttributes` set - `threshold` was `threhsold`.
I've also added a test to make sure no typos creep in again.
> fix typo in observed attributes

- src/relative-time-element.ts
- test/relative-time.js
We can get into some difficult conditions when frameworks from the outside try to set attributes multiple times because of multiple renders (e.g. react), which can cause the element to stop updating or update over eagerly.
This fix changes the update cycle so that updates to attributes _during_ the `update()` call won't cause `attributeChangedCallback` to update, but meanwhile re-setting `title` to its own contents wont flip the `#customTitle` flag causing updates to stop.
> avoid updating during update call

- src/relative-time-element.ts
- test/local-time.js
- test/relative-time.js
- test/time-ago.js
- test/time-until.js
- test/title-format.js
Following on from https://github.com/github/relative-time-element/pull/215, we can see that applying multiple properties can cause the time to update multiple times in quick succession. While this isn't a problem with 1 or 2 heavily customised elements on a page, it can quickly add up when calculating 100 or 1000 heavily customised elements on a page, and can contribute to TBT.
It's fairly simple to work around this; we can defer the `update()` call within `attributeChangedCallback` to only execute _after_ a Promise tick, and only if there isn't one queued up. This means multiple calls to setAttribute will cause the element to queue up a single batch call, and once the Promise has been resolved, it will update all properties at once.
I've added a test that demonstrates this effect - …
> Switch to promise batching on attributechangedcallback

- .eslintrc.json
- src/local-time-element-define.ts
- src/relative-time-element-define.ts
- src/time-ago-element-define.ts
- src/time-until-element-define.ts
Okay after a bit of a battle I managed to conjur the right typescript incantations which enables us to have operational typescript types, while also not _requiring_ JSX or React types to be installed.
This is a re-opening of https://github.com/github/relative-time-element/pull/213. Something @koddsson asked in hat PR but I didn't answer:
> Are we planning to auto-generate these in the future? I think that could be cool with the Custom Element Manifest if possible. Then it should be trivial to add other bindings for other frameworks as well and we don't have to manually maintain these bindings.
We could definitely take a look at this but in other frameworks this isn't really an issue as they either support custom elements well enough to not require this additional support scaffolding …
> add JSX IntrinsicElement types

- src/datetimeformat-ponyfill.ts
- src/index.ts
- src/local-time-element-define.ts
- src/local-time-element.ts
- src/relative-time-element.ts
- src/relative-time-ponyfill.ts
- src/time-ago-element-define.ts
- src/time-ago-element.ts
- src/time-until-element-define.ts
- src/time-until-element.ts
- test/constructor.js
- test/title-format.js
This PR is a BREAKING CHANGE, in which we `console.warn` on all deprecated features, which we plan to remove in the next version, `v4.0.0`.
The following features are to be deprecated in `v4.0.0`:
- The `local-time` element will be removed.
- The `time-ago` element will be removed.
- The `time-until` element will be removed.
- `getFormattedTitle` will be private. 
- `getFormattedDate` will be private. 
- `format` will no longer accept a `strftime` compatible format. Instead, any value other than `'micro'`, `'elapsed'` will revert to the string `'auto'`
- the `Intl.DateTimeFormat` constructor will not be ponyfilled, and so in environments without this constructor, the 
element will fall back to provided text.
- the `Intl.RelativeTimeFormat` constructor will not be ponyfilled, and so in …
> Warn on use of deprecated elements, functions and properties

- custom-elements-manifest.config.js
- package-lock.json
- package.json
- src/duration.ts
- src/relative-time-element-define.ts
- src/relative-time-element.ts
- test/duration-format.ts
- test/duration.ts
- test/relative-time.js
- web-test-runner.config.js
This upgrades all development dependencies to their latest versions, which also requires some small changes the code base. Most notably:
- `@github/prettier-config` gets an upgrade which requires trailing commas in objects and function params. So those have been added
- `typescript` gets an upgrade and no longer likes the `JSX.IntrinsicElements['span']` call without knowing what `JSX.IntrinsicElements` is, so the definition has had to be altered to include `type JSXBase` which selects `JSX.InstrinsicElements | Record<string, Record<string, unknown>>` This allows `JSXBaseElement` to resolve to the same as it always did, `JSX.IntrinsicElements['span'] | Record<string, unknown>`
> Upgrade all deps

- README.md
- src/relative-time-element.ts
- test/relative-time.js
This adds the `formatStyle` attribute. See #220 
Adding this attribute will allow us to separate the formatting style from the format. Right now this just gets applied to `RelativeTimeFormat`, and uses the default option of `long`.
> add formatStyle attribute

- README.md
- src/duration-format-ponyfill.ts
- src/duration-format.ts
- src/duration.ts
- src/relative-time-element.ts
- test/duration-format-ponyfill.ts
- test/duration.ts
This PR adds a ponyfill for the new [`Intl.DurationFormat`](https://tc39.es/proposal-intl-duration-format/) constructor, which can be used to take a `Duration` object (the spec asks for a Temporal Duration object, but our `Duration` object is similar enough to work), and convert it into a localised list of names, e.g `P1Y2D` becomes `1 year, 2 days`. This also has a `narrow` format which would display as `1y 2d`. 
The ponyfill uses [`Intl.NumberFormat`](https://caniuse.com/mdn-javascript_builtins_intl_numberformat_format) which has been supported in browsers as far back as IE11. It also uses [`Intl.ListFormat`](https://caniuse.com/mdn-javascript_builtins_intl_numberformat_format) with a fallback to a class which effectively does `.join(', ')`. This is mostly because this is not as well …
> Move elapsed to duration

- README.md
- src/relative-time-element.ts
- test/duration.ts
- test/relative-time.js
This PR supports the new formats details in #220;
`format=datetime` will always display the full datetime. With this option set, the `prefix` defaults to `''` and the `weekday` and `month` values will default to the `formatStyle` value (which defaults to `short`). Meaning dates like `Fri, Dec 9 2022`.
`format=relative` acts like `format=auto`. Relative days (`today`, `yesterday`, `3 days ago`) will be displayed until the threshold is met, at which point it will use `datetime` style format, except `prefix` will be `'on'`, `weekday` will be `undefined` and `month` will be `formatStyle` (which defaults to `short`). This means dates beyond threshold will display like `Dec 9 2022`
`format=duration` acts like `format=elapsed`, except the default `formatStyle` is `'long'`, not `'narrow'`, as …
> support format=datetime/format=relative/format=duration

- examples/index.html
The examples page is quite out of date. This fixes it up to use the modern formats.
> fix up examples page

- .github/workflows/publish.yml
This PR adds a job to publish the `relative-time-element` package to GPR (GitHub Private Registry) because having the package only on NPM under `@github` scope causes an issue for some repos (memex, dotcom) whose automation dependency management are configured to install these private packages from GRP in the @github scope not NPM @github  scope.
For more info, see [this slack thread](https://github.slack.com/archives/CMZ4DC9BL/p1670852971245929)
> Add a job to publish the package in GPR

- .github/workflows/publish.yml
`Publish` action is [failed](https://github.com/github/relative-time-element/actions/runs/3689762049) due to unknown `create-release` action. This PR removes this because we manage the releases manually in this repo and we don't need `needs`. Please let me know if I miss anything or misinterpreted the error message!
> Actions: Remove `needs`  from the publish-github job

- src/relative-time-element.ts
- test/relative-time.js
When the elements `lang` attribute is set to an empty string (`''`) this can cause the element to fail because `''` is not a valid language tag.
This changes the element to use logical or (`||`) to ensure that falsy string values are ignored. In addition, to avoid `lang=''` being treated as `'default'`, it will attempt to revert to the document's `lang` if it cannot find a reasonable `lang` attribute to use up the tree. This way if `<html lang="...">` is valid, it will use that.
> avoid throwing errors for empty lang attributes

- src/relative-time-element.ts
- test/relative-time.js
I've noticed that there's a typo in the year setter, preventing the ability to customize the format for the year (especially when using the `datetime` format) - it affects the day format instead. 
One test (unrelated) also expected its output to omit the date because of the default behavior when the current year is the same as the date's year, so the second commit here addresses that failing test.
> Year setter typo

- src/duration.ts
- test/duration.ts
- test/relative-time.js
Currently the main release of relative time uses a 90% rounding rule for dates.
Relative times are colloquial and so every user interprets them in subtly different ways. There are a few techniques we have used in the past:
- We go on the literal date unit. So at 12:01AM a post from 2 minutes prior would say "a day ago". A post on the 31st December, when read on 1st Jan, would say "last year", which feels inaccurate.
- We round units to some amount, so if the delta is 2 minutes we say "2 minutes ago" until minutes can be rounded up to hours at which point we can say "1 hour ago". We can pick the threshold for this...
- A threshold of 50% would mean something 30 minutes ago would be "1 hour ago", and something 6 months ago would say "last year". Having a low threshold for larger durations …
> update rounding rules for months/years in Duration

- .github/workflows/publish.yml
The new version has provenance support built in.
https://github.com/npm/cli/pull/6163
> Update to use latest npm CLI release

- src/duration.ts
- test/duration.ts
Fixes round to single unit function returns `nows` when durations exceeds -27 days in the same month.
> fix: fixes round to string unit

- src/duration.ts
- test/duration.ts
- test/relative-time.js
Some nearby dates get aggressively compressed to `yesterday` when they're over 1 day away (e.g. something that is 1 day and 20 hours ago will say `yesterday` when it probably should say `2 days ago`).
This fixes that.
> fix aggressive compression of hours into a single day

- src/relative-time-element-define.ts
- src/relative-time-element.ts
This makes a few small tweaks to how we define elements. 
It adds a `define()` static member to the `RelativeTimeElement` class, which allows changing of tag/registry. It calls that method in the `relative-time-element-define` file.
This also exports the class as both named and default exports. We may drop the default export at a future date.
> add define static method

- src/duration.ts
- test/duration.ts
- test/relative-time.js
Fixes #270
This uses calendar math for differences with a larger precision than 27 days.
> round years using calendar years only

- src/relative-time-element.ts
- test/relative-time.js
This turns "now" into "today", "this month", "this hour", etc.
Fixes #279.
Whether "this minute" is better than "now" is debatable, but I feel like that debate should happen in the CLDR data that drives `Intl.RelativeTimeFormat.format(0, 'minute')` rather than in this library.
> Express "0 precision-units away" appropriately for the precision.

- README.md
currently it copies the `$` when copying
> fix: remove dollar sign from command

- README.md
- examples/index.html
- src/relative-time-element.ts
- test/relative-time.js
Related to https://github.com/github/accessibility-audits/issues/5633 & https://github.com/github/accessibility-audits/issues/5524.
Adds a flag to optionally hide the inaccessible `title` attribute. We will use this in the Primer components so we can add an accessible Tooltip element instead for interactive elements.
> Adds flag to optionally hide title attribute

- src/relative-time-element.ts
Calculate the new title, just don’t update the `title` attribute. This makes the `'relative-time-updated'` event fire, even if `noTitle` is set.
> fix: Move `noTitle` conditional.

- src/duration.ts
- test/duration.ts
- test/relative-time.js
Right now relative month time frames are not calculated correctly if the relative duration would put it past the end of a shorter month causing #281, e.g. something like "May 31 minus 1 month" (see <https://github.com/github/relative-time-element/issues/281#issuecomment-2142961052> for more explanation of why)
This PR fixes these sorts of anomalies by correcting "May 31 minus 1 month" to be equal to "April 30" rather than "May 1"
I've added test cases as well to affirm this new expected behavior (and made duration test cases work when two test cases have equivalent duration but relativeTo date is different). Please look through the test cases, though, to make sure these are all intended consequences
Fixes #281
> Correctly count month durations relative to the end of longer months

- examples/index.html
- src/relative-time-element.ts
- test/relative-time.js
@cheshire137 exposed an interesting timing flaw in #289. If you set a null/empty datetime the `#updating` Promise (which tries to batch updates) can be left as a resolved promise due to an early return in `update()`.
The last line of `update()` sets `#updating` to false:
https://github.com/github/relative-time-element/blob/15ca61e1992f39f242aa4de0b35c14ce76062990/src/relative-time-element.ts#L475-L476
However if `update()` is called while the `date` is `null` then it hits this early return:
https://github.com/github/relative-time-element/blob/15ca61e1992f39f242aa4de0b35c14ce76062990/src/relative-time-element.ts#L438-L441
That early return never sets `#updating = false`, and so when the date is set again we skip a call to `update()` as it looks like we're in an update batch already: …
> ensure #updating doesnt hang updates

- src/relative-time-element.ts
- test/relative-time.js
Closes https://github.com/github/primer/issues/4409
Fixes error thrown when an invalid locale is passed to the `Intl` functions by wrapping it in Try/Catch. When the call fails (locale is invalid), the default locale will be used
> fix: wrap Intl.<>() calls in try/catch

- test/relative-time.js
This just alters a test to get the main branch green. This test will likely fail again at some point but let's worry about that later, after we've cleared the current PRs on deck.
> get main branch green

- src/duration.ts
- test/duration.ts
(This is part of a set of multiple pull requests looking to overhaul the calculation functions.)
When the duration to be applied is negative, this pull request makes the application order of the components reversed compared to when the duration is positive, so that adding a duration to a date then subtracting the same amount yields the same date.
**Note:** One test is failing on my end from the current upstream code:
```
relative-time > [tense=future] > micro formats years
AssertionError: expected '3y' to equal '2y'
+ expected - actual
- 3y
+ 2y
```
This is caused by the current implementation of `roundToNearestUnit` computing the future date to be in 2027, resulting in a 3-year difference as it only considers the year alone in this case. This will be fixed with a reimplementation of the …
> Make `applyDuration` reversible

- test/relative-time.js
Noticed this was failing in newer PRs so updated it to pass. Not sure what the correct value is here but `10y` seemed to make sense because the test was subtracting 10 years.
> test: update assertion for test

- package-lock.json
- package.json
- src/relative-time-element-define.ts
Fixes https://github.com/github/relative-time-element/issues/304
I had to add a `@ts-expect-error` comment since otherwise the typechecker would complain about missing `react` as a dependency.
> Declare `relative-element` under React.JSX to fix React 19 compatibility

- package-lock.json
- package.json
- src/relative-time-element-define.ts
Reverts github/relative-time-element#305
These changes turned out to not be compatible with non-react projects (sample test: https://github.com/primer/view_components/pull/3472)
Reverting
> Revert "Declare `relative-element` under React.JSX to fix React 19 compatibility"

- examples/index.html
- src/relative-time-element.ts
- test/relative-time.js
Relates to: https://github.com/github/pull-requests/issues/17192
When `aria-hidden="true"` is set on an relative-time element, the attribute doesn't always persist into the shadow root. As a result, even when `aria-hidden` is applied, the text rendered in relative-time can end up composing the accessible name (instead of being hidden from the AT tree).
This makes update to render the text content within `aria-hidden="true"`, when `aria-hidden="true"` is set on the shadow root. 
Before (no sound):
https://github.com/user-attachments/assets/5a049c15-8ec7-4a7f-be6e-97c3b149f389
video description: I'm on the demo page with the developer console open. The markup shows `aria-hidden` being toggled between true and false relative-time upon pressing the button. I switch to the accessibility tree …
> fix: Ensure aria-hidden applies to shadow root

- README.md
- src/relative-time-element.ts
- test/relative-time.js
> feat: add support for time-zone attribute
